---
title: "Simulation Tables"
author: "SEOYEON CHOI"
date: "2023-05-17"
categories:
  - ITSTGCN
---

> Simulation Tables

# import

In [217]:
import pandas as pd

# Fivenodes

In [218]:
data_fivenodes= pd.read_csv('./simulation_results/Real_simulation/fivedones_Simulation.csv')

## Baseline

In [219]:
pd.merge(data_fivenodes.query("mtype!='rand' and mtype!='block'").groupby(['nof_filters','method','lags'])['mse'].mean().reset_index(),
         data_fivenodes.query("mtype!='rand' and mtype!='block'").groupby(['nof_filters','method','lags'])['mse'].std().reset_index(),
         on=['method','nof_filters','lags']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3)

   nof_filters    method  lags   mean    std
0         12.0  IT-STGCN     2  1.168  0.030
1         12.0     STGCN     2  1.173  0.036
2         16.0  IT-STGCN     2  1.166  0.039
3         16.0     STGCN     2  1.165  0.040

In [220]:
pd.merge(data_fivenodes.query("mtype!='rand' and mtype!='block'").groupby(['nof_filters','lags'])['mse'].mean().reset_index(),
         data_fivenodes.query("mtype!='rand' and mtype!='block'").groupby(['nof_filters','lags'])['mse'].std().reset_index(),
         on=['nof_filters','lags']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3)

   nof_filters  lags   mean    std
0         12.0     2  1.170  0.033
1         16.0     2  1.165  0.039

## Random

In [221]:
data_fivenodes.query("mtype=='rand'and method=='GNAR'")['mse'].unique().round(2)

array([1.41])

In [222]:
pd.merge(data_fivenodes.query("mtype=='rand'").groupby(['mrate','nof_filters','method','lags'])['mse'].mean().reset_index(),
         data_fivenodes.query("mtype=='rand'").groupby(['mrate','nof_filters','method','lags'])['mse'].std().reset_index(),
         on=['method','nof_filters','mrate','lags']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3).query("nof_filters==12")

    mrate  nof_filters    method  lags   mean    std
0    0.70         12.0  IT-STGCN     2  1.200  0.070
1    0.70         12.0     STGCN     2  1.213  0.083
4    0.75         12.0  IT-STGCN     2  1.188  0.060
5    0.75         12.0     STGCN     2  1.239  0.102
8    0.80         12.0  IT-STGCN     2  1.221  0.083
9    0.80         12.0     STGCN     2  1.226  0.105
12   0.85         12.0  IT-STGCN     2  1.227  0.085
13   0.85         12.0     STGCN     2  1.291  0.252

In [223]:
pd.merge(data_fivenodes.query("mtype=='rand'").groupby(['mrate','nof_filters','method','lags'])['mse'].mean().reset_index(),
         data_fivenodes.query("mtype=='rand'").groupby(['mrate','nof_filters','method','lags'])['mse'].std().reset_index(),
         on=['method','nof_filters','mrate','lags']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3).query("nof_filters!=12")

    mrate  nof_filters    method  lags   mean    std
2    0.70         16.0  IT-STGCN     2  1.201  0.068
3    0.70         16.0     STGCN     2  1.227  0.094
6    0.75         16.0  IT-STGCN     2  1.231  0.110
7    0.75         16.0     STGCN     2  1.201  0.072
10   0.80         16.0  IT-STGCN     2  1.232  0.092
11   0.80         16.0     STGCN     2  1.292  0.148
14   0.85         16.0  IT-STGCN     2  1.286  0.297
15   0.85         16.0     STGCN     2  1.362  0.239

## Block

In [224]:
data_fivenodes.query("mtype=='block'and method=='GNAR'")['mse'].unique().round(2)

array([1.41])

In [225]:
pd.merge(data_fivenodes.query("mtype=='block'").groupby(['mrate','nof_filters','method'])['mse'].mean().reset_index(),
         data_fivenodes.query("mtype=='block'").groupby(['mrate','nof_filters','method'])['mse'].std().reset_index(),
         on=['method','nof_filters','mrate']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3)

   mrate  nof_filters    method   mean    std
0  0.125         12.0  IT-STGCN  4.308  3.333
1  0.125         12.0     STGCN  6.722  5.755
2  0.125         16.0  IT-STGCN  4.633  3.737
3  0.125         16.0     STGCN  6.858  5.814
4  0.300         12.0  IT-STGCN  1.178  0.032
5  0.300         12.0     STGCN  1.232  0.040
6  0.300         16.0  IT-STGCN  1.163  0.050
7  0.300         16.0     STGCN  1.232  0.053

---

epoch 별 보기

In [226]:
df1 = pd.read_csv('./simulation_results/fivenodes/fivenodes_STGCN_ITSTGCN_random_epoch50.csv')
df2 = pd.read_csv('./simulation_results/fivenodes/fivenodes_STGCN_ITSTGCN_random_epoch100.csv')
df3 = pd.read_csv('./simulation_results/fivenodes/fivenodes_STGCN_ITSTGCN_random_epoch150.csv')
df4 = pd.read_csv('./simulation_results/fivenodes/fivenodes_STGCN_ITSTGCN_random_epoch200.csv')

In [227]:
df_gnar = pd.read_csv('./simulation_results/fivenodes/fivenodes_GNAR_random.csv')

In [228]:
data = pd.concat([df1,df2,df3,df4,df_gnar],axis=0)

STGCN은 nearest에서 mse가 낮았다.

In [229]:
data.query("method=='STGCN' and mtype=='rand' and mrate==0.8 and lags==2 and inter_method=='linear' and nof_filters==4").\
groupby(['method','epoch','mrate','lags','nof_filters','inter_method'])['mse'].mean().reset_index()['mse'].mean()

1.182556539773941

In [230]:
data.query("method=='STGCN' and mtype=='rand' and mrate==0.8 and lags==2 and inter_method=='linear' and nof_filters==4").\
groupby(['method','epoch','mrate','lags','nof_filters','inter_method'])['mse'].mean().reset_index()['mse'].std()

0.012169932740213692

In [231]:
data.query("method=='IT-STGCN' and mtype=='rand' and mrate==0.8 and lags==2 and inter_method=='linear' and nof_filters==4").\
groupby(['method','epoch','mrate','lags','nof_filters','inter_method'])['mse'].mean().reset_index()['mse'].mean()

1.1747438261906304

In [232]:
data.query("method=='IT-STGCN' and mtype=='rand' and mrate==0.8 and lags==2 and inter_method=='linear' and nof_filters==4").\
groupby(['method','epoch','mrate','lags','nof_filters','inter_method'])['mse'].mean().reset_index()['mse'].std()

0.007602895892378366

# ChickenpoxDatasetLoader mrate 높여서 해보기

In [233]:
data_chickenpox = pd.read_csv('./simulation_results/Real_simulation/chikenpox_Simulation.csv')

In [234]:
data_chickenpox2 = pd.read_csv('./simulation_results/Real_simulation/chikenpox_Simulation_sndblock.csv')

## Baseline

In [235]:
pd.merge(data_chickenpox.query("mtype!='rand' and mtype!='block'").groupby(['nof_filters','method'])['mse'].mean().reset_index(),
         data_chickenpox.query("mtype!='rand' and mtype!='block'").groupby(['nof_filters','method'])['mse'].std().reset_index(),
         on=['method','nof_filters']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3)

   nof_filters    method   mean    std
0         16.0  IT-STGCN  1.008  0.010
1         16.0     STGCN  1.009  0.008
2         24.0  IT-STGCN  1.013  0.008
3         24.0     STGCN  1.011  0.009
4         32.0  IT-STGCN  1.014  0.011
5         32.0     STGCN  1.013  0.012

## Random

In [236]:
data_chickenpox.query("mtype=='rand'and method=='GNAR'")['mse'].unique().round(3)

array([1.427])

In [237]:
pd.merge(data_chickenpox.query("mtype=='rand'").groupby(['mrate','inter_method','nof_filters','method'])['mse'].mean().reset_index(),
         data_chickenpox.query("mtype=='rand'").groupby(['mrate','inter_method','nof_filters','method'])['mse'].std().reset_index(),
         on=['method','inter_method','mrate','nof_filters']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3).query("mrate==0.3")

    mrate inter_method  nof_filters    method   mean    std
0     0.3        cubic         16.0  IT-STGCN  1.019  0.011
1     0.3        cubic         16.0     STGCN  1.059  0.013
2     0.3        cubic         24.0  IT-STGCN  1.019  0.008
3     0.3        cubic         24.0     STGCN  1.058  0.013
4     0.3        cubic         32.0  IT-STGCN  1.022  0.010
5     0.3        cubic         32.0     STGCN  1.062  0.013
6     0.3       linear         16.0  IT-STGCN  1.015  0.009
7     0.3       linear         16.0     STGCN  1.040  0.014
8     0.3       linear         24.0  IT-STGCN  1.020  0.011
9     0.3       linear         24.0     STGCN  1.039  0.012
10    0.3       linear         32.0  IT-STGCN  1.024  0.014
11    0.3       linear         32.0     STGCN  1.043  0.012

In [238]:
pd.merge(data_chickenpox.query("mtype=='rand'").groupby(['mrate','inter_method','nof_filters','method'])['mse'].mean().reset_index(),
         data_chickenpox.query("mtype=='rand'").groupby(['mrate','inter_method','nof_filters','method'])['mse'].std().reset_index(),
         on=['method','inter_method','mrate','nof_filters']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3).query("mrate==0.4")

    mrate inter_method  nof_filters    method   mean    std
12    0.4        cubic         16.0  IT-STGCN  1.021  0.009
13    0.4        cubic         16.0     STGCN  1.084  0.025
14    0.4        cubic         24.0  IT-STGCN  1.025  0.011
15    0.4        cubic         24.0     STGCN  1.095  0.021
16    0.4        cubic         32.0  IT-STGCN  1.025  0.013
17    0.4        cubic         32.0     STGCN  1.099  0.025
18    0.4       linear         16.0  IT-STGCN  1.020  0.009
19    0.4       linear         16.0     STGCN  1.051  0.014
20    0.4       linear         24.0  IT-STGCN  1.020  0.012
21    0.4       linear         24.0     STGCN  1.053  0.014
22    0.4       linear         32.0  IT-STGCN  1.029  0.014
23    0.4       linear         32.0     STGCN  1.054  0.014

In [239]:
pd.merge(data_chickenpox.query("mtype=='rand'").groupby(['mrate','inter_method','nof_filters','method'])['mse'].mean().reset_index(),
         data_chickenpox.query("mtype=='rand'").groupby(['mrate','inter_method','nof_filters','method'])['mse'].std().reset_index(),
         on=['method','inter_method','mrate','nof_filters']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3).query("mrate==0.5")

    mrate inter_method  nof_filters    method   mean    std
24    0.5        cubic         16.0  IT-STGCN  1.027  0.012
25    0.5        cubic         16.0     STGCN  1.128  0.042
26    0.5        cubic         24.0  IT-STGCN  1.031  0.013
27    0.5        cubic         24.0     STGCN  1.126  0.032
28    0.5        cubic         32.0  IT-STGCN  1.032  0.015
29    0.5        cubic         32.0     STGCN  1.129  0.026
30    0.5       linear         16.0  IT-STGCN  1.026  0.014
31    0.5       linear         16.0     STGCN  1.071  0.016
32    0.5       linear         24.0  IT-STGCN  1.029  0.013
33    0.5       linear         24.0     STGCN  1.073  0.017
34    0.5       linear         32.0  IT-STGCN  1.037  0.016
35    0.5       linear         32.0     STGCN  1.080  0.015

## Block

In [240]:
data_chickenpox.query("mtype=='block'and method=='GNAR'")['mse'].unique()

array([1.42749429])

In [241]:
data_chickenpox2.query("mtype=='block'and method=='GNAR'")['mse'].unique()

array([1.42749429])

In [242]:
pd.merge(data_chickenpox.query("mtype=='block'").groupby(['inter_method','mrate','nof_filters','method'])['mse'].mean().reset_index(),
         data_chickenpox2.query("mtype=='block'").groupby(['inter_method','mrate','nof_filters','method'])['mse'].std().reset_index(),
         on=['method','inter_method','mrate','nof_filters']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3)

   inter_method  mrate  nof_filters    method   mean    std
0         cubic  0.288         16.0  IT-STGCN  1.052  3.588
1         cubic  0.288         16.0     STGCN  1.052  5.963
2         cubic  0.288         24.0  IT-STGCN  1.048  2.650
3         cubic  0.288         24.0     STGCN  1.044  3.515
4         cubic  0.288         32.0  IT-STGCN  1.047  1.485
5         cubic  0.288         32.0     STGCN  1.040  2.448
6        linear  0.288         16.0  IT-STGCN  1.008  0.007
7        linear  0.288         16.0     STGCN  1.011  0.008
8        linear  0.288         24.0  IT-STGCN  1.014  0.006
9        linear  0.288         24.0     STGCN  1.014  0.011
10       linear  0.288         32.0  IT-STGCN  1.011  0.009
11       linear  0.288         32.0     STGCN  1.014  0.010

# PedalMeDatasetLoader (lags=4)

In [243]:
data_pedalme = pd.read_csv('./simulation_results/Real_simulation/pedalme_Simulation.csv')

In [244]:
data_pedalme2 = pd.read_csv('./simulation_results/Real_simulation/pedalme_Simulation_sndbaseline.csv')

## Baseline

In [245]:
pd.merge(data_pedalme.query("mtype!='rand' and mtype!='block'").groupby(['lags','nof_filters','method'])['mse'].mean().reset_index(),
         data_pedalme.query("mtype!='rand' and mtype!='block'").groupby(['lags','nof_filters','method'])['mse'].std().reset_index(),
         on=['method','lags','nof_filters']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3)

   lags  nof_filters    method   mean    std
0     4         12.0  IT-STGCN  1.239  0.040
1     4         12.0     STGCN  1.269  0.042
2     8         12.0  IT-STGCN  1.455  0.100
3     8         12.0     STGCN  1.494  0.117

잘못 돌렸나 비교하느라 두 번 돌림..!

In [246]:
pd.merge(data_pedalme2.query("mtype!='rand' and mtype!='block'").groupby(['lags','nof_filters','method'])['mse'].mean().reset_index(),
         data_pedalme2.query("mtype!='rand' and mtype!='block'").groupby(['lags','nof_filters','method'])['mse'].std().reset_index(),
         on=['method','lags','nof_filters']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3)

   lags  nof_filters    method   mean    std
0     4           12  IT-STGCN  1.244  0.040
1     4           12     STGCN  1.273  0.039
2     8           12  IT-STGCN  1.464  0.114
3     8           12     STGCN  1.505  0.108

## Random

In [247]:
pd.merge(data_pedalme.query("mtype=='rand'").groupby(['mrate','lags','inter_method','method'])['mse'].mean().reset_index(),
         data_pedalme.query("mtype=='rand'").groupby(['mrate','lags','inter_method','method'])['mse'].std().reset_index(),
         on=['method','mrate','lags','inter_method']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3).query("mrate==0.3")

   mrate  lags inter_method    method   mean    std
0    0.3     4        cubic      GNAR  1.303  0.000
1    0.3     4        cubic  IT-STGCN  1.314  0.109
2    0.3     4        cubic     STGCN  1.363  0.115
3    0.3     4       linear      GNAR  1.303  0.000
4    0.3     4       linear  IT-STGCN  1.323  0.094
5    0.3     4       linear     STGCN  1.380  0.127
6    0.3     8        cubic  IT-STGCN  1.538  0.188
7    0.3     8        cubic     STGCN  1.451  0.255
8    0.3     8       linear  IT-STGCN  1.526  0.167
9    0.3     8       linear     STGCN  1.448  0.184

In [248]:
pd.merge(data_pedalme.query("mtype=='rand'").groupby(['mrate','lags','inter_method','method'])['mse'].mean().reset_index(),
         data_pedalme.query("mtype=='rand'").groupby(['mrate','lags','inter_method','method'])['mse'].std().reset_index(),
         on=['method','mrate','lags','inter_method']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3).query("mrate==0.4")

    mrate  lags inter_method    method   mean    std
10    0.4     4        cubic      GNAR  1.303  0.000
11    0.4     4        cubic  IT-STGCN  1.331  0.112
12    0.4     4        cubic     STGCN  1.342  0.108
13    0.4     4       linear      GNAR  1.303  0.000
14    0.4     4       linear  IT-STGCN  1.375  0.154
15    0.4     4       linear     STGCN  1.397  0.193
16    0.4     8        cubic  IT-STGCN  1.540  0.223
17    0.4     8        cubic     STGCN  1.471  0.208
18    0.4     8       linear  IT-STGCN  1.485  0.233
19    0.4     8       linear     STGCN  1.443  0.187

In [249]:
pd.merge(data_pedalme.query("mtype=='rand'").groupby(['mrate','lags','inter_method','method'])['mse'].mean().reset_index(),
         data_pedalme.query("mtype=='rand'").groupby(['mrate','lags','inter_method','method'])['mse'].std().reset_index(),
         on=['method','mrate','lags','inter_method']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3).query("mrate==0.5")

    mrate  lags inter_method    method   mean    std
20    0.5     4        cubic      GNAR  1.303  0.000
21    0.5     4        cubic  IT-STGCN  1.328  0.108
22    0.5     4        cubic     STGCN  1.367  0.114
23    0.5     4       linear      GNAR  1.303  0.000
24    0.5     4       linear  IT-STGCN  1.377  0.138
25    0.5     4       linear     STGCN  1.326  0.129
26    0.5     8        cubic  IT-STGCN  1.506  0.151
27    0.5     8        cubic     STGCN  1.424  0.135
28    0.5     8       linear  IT-STGCN  1.544  0.176
29    0.5     8       linear     STGCN  1.539  0.196

In [250]:
pd.merge(data_pedalme.query("mtype=='rand'").groupby(['mrate','lags','inter_method','method'])['mse'].mean().reset_index(),
         data_pedalme.query("mtype=='rand'").groupby(['mrate','lags','inter_method','method'])['mse'].std().reset_index(),
         on=['method','mrate','lags','inter_method']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3).query("mrate==0.6")

    mrate  lags inter_method    method   mean    std
30    0.6     4        cubic      GNAR  1.303  0.000
31    0.6     4        cubic  IT-STGCN  1.300  0.063
32    0.6     4        cubic     STGCN  1.352  0.106
33    0.6     4       linear      GNAR  1.303  0.000
34    0.6     4       linear  IT-STGCN  1.416  0.169
35    0.6     4       linear     STGCN  1.326  0.106
36    0.6     8        cubic      GNAR  1.382  0.000
37    0.6     8        cubic  IT-STGCN  1.435  0.261
38    0.6     8        cubic     STGCN  1.542  0.194
39    0.6     8       linear      GNAR  1.382  0.000
40    0.6     8       linear  IT-STGCN  1.514  0.270
41    0.6     8       linear     STGCN  1.477  0.196

## Block

In [251]:
pd.merge(data_pedalme.query("mtype=='block'").groupby(['mrate','lags','inter_method','method'])['mse'].mean().reset_index(),
         data_pedalme.query("mtype=='block'").groupby(['mrate','lags','inter_method','method'])['mse'].std().reset_index(),
         on=['method','mrate','lags','inter_method']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3)

    mrate  lags inter_method    method   mean    std
0   0.138     8        cubic      GNAR  1.382  0.000
1   0.138     8        cubic  IT-STGCN  1.346  0.159
2   0.138     8        cubic     STGCN  1.332  0.090
3   0.138     8       linear      GNAR  1.382  0.000
4   0.143     4        cubic      GNAR  1.303  0.000
5   0.143     4        cubic  IT-STGCN  1.284  0.053
6   0.143     4        cubic     STGCN  1.288  0.071
7   0.143     4       linear      GNAR  1.303  0.000
8   0.276     8        cubic      GNAR  1.382  0.000
9   0.276     8        cubic  IT-STGCN  1.440  0.110
10  0.276     8        cubic     STGCN  1.231  0.051
11  0.276     8       linear      GNAR  1.382  0.000
12  0.276     8       linear  IT-STGCN  1.693  0.159
13  0.276     8       linear     STGCN  1.622  0.123
14  0.286     4        cubic      GNAR  1.303  0.000
15  0.286     4        cubic  IT-STGCN  1.304  0.050
16  0.286     4        cubic     STGCN  1.377  0.061
17  0.286     4       linear      GNAR  1.303  0.000
18  0.286     4       linear  IT-STGCN  1.335  0.062
19  0.286     4       linear     STGCN  1.350  0.056

## W_st

In [282]:
data_pedalme_wst = pd.read_csv('./simulation_results/Real_simulation/pedalme_Simulation_itstgcnsnd.csv')

In [283]:
pd.merge(data_pedalme_wst.query("mtype=='rand'").groupby(['mrate','lags','inter_method','method'])['mse'].mean().reset_index(),
         data_pedalme_wst.query("mtype=='rand'").groupby(['mrate','lags','inter_method','method'])['mse'].std().reset_index(),
         on=['method','mrate','lags','inter_method']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3).query("lags==4")

    mrate  lags inter_method    method   mean    std
0     0.3     4        cubic  IT-STGCN  1.353  0.141
1     0.3     4        cubic     STGCN  1.360  0.131
2     0.3     4       linear  IT-STGCN  1.337  0.122
3     0.3     4       linear     STGCN  1.353  0.117
4     0.3     4      nearest  IT-STGCN  1.316  0.122
5     0.3     4      nearest     STGCN  1.403  0.134
12    0.4     4        cubic  IT-STGCN  1.332  0.166
13    0.4     4        cubic     STGCN  1.344  0.123
14    0.4     4       linear  IT-STGCN  1.355  0.139
15    0.4     4       linear     STGCN  1.393  0.168
16    0.4     4      nearest  IT-STGCN  1.386  0.128
17    0.4     4      nearest     STGCN  1.341  0.129
24    0.5     4        cubic  IT-STGCN  1.312  0.152
25    0.5     4        cubic     STGCN  1.362  0.129
26    0.5     4       linear  IT-STGCN  1.344  0.177
27    0.5     4       linear     STGCN  1.335  0.117
28    0.5     4      nearest  IT-STGCN  1.335  0.153
29    0.5     4      nearest     STGCN  1.350  0.129
36    0.6     4        cubic  IT-STGCN  1.346  0.151
37    0.6     4        cubic     STGCN  1.398  0.103
38    0.6     4       linear  IT-STGCN  1.365  0.177
39    0.6     4       linear     STGCN  1.353  0.087
40    0.6     4      nearest  IT-STGCN  1.402  0.269
41    0.6     4      nearest     STGCN  1.339  0.111
48    0.7     4        cubic  IT-STGCN  1.377  0.173
49    0.7     4        cubic     STGCN  1.363  0.097
50    0.7     4       linear  IT-STGCN  1.355  0.144
51    0.7     4       linear     STGCN  1.288  0.063
52    0.7     4      nearest  IT-STGCN  1.383  0.157
53    0.7     4      nearest     STGCN  1.334  0.124

In [290]:
pd.merge(data_pedalme_wst.query("mtype=='block'").groupby(['mrate','lags','inter_method','method'])['mse'].mean().reset_index(),
         data_pedalme_wst.query("mtype=='block'").groupby(['mrate','lags','inter_method','method'])['mse'].std().reset_index(),
         on=['method','mrate','lags','inter_method']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3).query("lags==4")

    mrate  lags inter_method    method   mean    std
6   0.286     4        cubic  IT-STGCN  1.260  0.063
7   0.286     4        cubic     STGCN  1.417  0.065
8   0.286     4       linear  IT-STGCN  1.276  0.065
9   0.286     4       linear     STGCN  1.288  0.055
10  0.286     4      nearest  IT-STGCN  1.275  0.061
11  0.286     4      nearest     STGCN  1.312  0.061

# WikiMathsDatasetLoader (lags=8)

In [254]:
data_wikimath = pd.read_csv('./simulation_results/Real_simulation/wikimath.csv')

In [255]:
data_wikimath_block = pd.read_csv('./simulation_results/Real_simulation/wikimath_block.csv')

## Baseline

In [256]:
data_wikimath.query("mrate==0").groupby(['lags','nof_filters','method'])['mse'].mean().reset_index().round(3)

   lags  nof_filters    method    mse
0     2         12.0  IT-STGCN  0.805
1     2         12.0     STGCN  0.800
2     4         12.0  IT-STGCN  0.776
3     4         12.0     STGCN  0.776

## Random

In [257]:
pd.merge(data_wikimath.query("mtype=='rand'").groupby(['mrate','lags','method'])['mse'].mean().reset_index(),
         data_wikimath.query("mtype=='rand'").groupby(['mrate','lags','method'])['mse'].std().reset_index(),
         on=['method','mrate','lags']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3)

    mrate  lags    method   mean    std
0     0.3     2      GNAR  1.296  0.000
1     0.3     2  IT-STGCN  0.818  0.018
2     0.3     2     STGCN  0.810  0.006
3     0.3     4      GNAR  1.255  0.000
4     0.3     4  IT-STGCN  0.803  0.016
5     0.3     4     STGCN  0.799  0.012
6     0.5     2      GNAR  1.296  0.000
7     0.5     2  IT-STGCN  0.832  0.020
8     0.5     2     STGCN  0.840  0.026
9     0.5     4      GNAR  1.255  0.000
10    0.5     4  IT-STGCN  0.822  0.009
11    0.5     4     STGCN  0.826  0.011

## Block

In [258]:
pd.merge(data_wikimath_block.query("mtype=='block'").groupby(['mrate','lags','method'])['mse'].mean().reset_index(),
         data_wikimath_block.query("mtype=='block'").groupby(['mrate','lags','method'])['mse'].std().reset_index(),
         on=['method','mrate','lags']).rename(columns={'mse_x':'mean','mse_y':'std'})

      mrate  lags    method      mean       std
0  0.003841     2  IT-STGCN  0.810475  0.033897
1  0.003841     2     STGCN  0.801502  0.015510
2  0.003841     4  IT-STGCN  0.779852  0.013188
3  0.003841     4     STGCN  0.779816  0.019309

## missing values on the same nodes

In [291]:
data_wikimath_st = pd.read_csv('./simulation_results/Real_simulation/wikimath_GSO_st.csv')

In [292]:
pd.merge(data_wikimath_st.groupby(['mrate','lags','method'])['mse'].mean().reset_index(),
        data_wikimath_st.groupby(['mrate','lags','method'])['mse'].std().reset_index(),
         on=['method','mrate','lags']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3)

   mrate  lags    method   mean    std
0  0.123     4  IT-STGCN  0.774  0.008
1  0.123     4     STGCN  0.766  0.010
2  0.738     4  IT-STGCN  0.893  0.019
3  0.738     4     STGCN  0.880  0.014

# WindmillOutputSmallDatasetLoader (lags=8)

In [293]:
data_windmillsmall = pd.read_csv('./simulation_results/Real_simulation/windmillsmall.csv')

In [294]:
data_windmillsmall_block = pd.read_csv('./simulation_results/Real_simulation/windmillsmall_block.csv')

## Baseline

In [295]:
data_windmillsmall.query("mrate==0").groupby(['lags','nof_filters','method'])['mse'].mean().reset_index().round(3)

   lags  nof_filters    method    mse
0     8         12.0  IT-STGCN  1.008
1     8         12.0     STGCN  1.001

## Random

In [296]:
pd.merge(data_windmillsmall.query("mtype=='rand'").groupby(['mrate','lags','method'])['mse'].mean().reset_index(),
         data_windmillsmall.query("mtype=='rand'").groupby(['mrate','lags','method'])['mse'].std().reset_index(),
         on=['method','mrate','lags']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3)

   mrate  lags    method   mean    std
0    0.7     8      GNAR  1.649  0.000
1    0.7     8  IT-STGCN  1.178  0.054
2    0.7     8     STGCN  1.410  0.075

## Block

In [297]:
pd.merge(data_windmillsmall_block.query("mtype=='block'").groupby(['mrate','lags','method'])['mse'].mean().reset_index(),
         data_windmillsmall_block.query("mtype=='block'").groupby(['mrate','lags','method'])['mse'].std().reset_index(),
         on=['method','mrate','lags']).rename(columns={'mse_x':'mean','mse_y':'std'}).round(3)

   mrate  lags    method   mean    std
0  0.325     8      GNAR  1.649  0.000
1  0.325     8  IT-STGCN  1.015  0.009
2  0.325     8     STGCN  1.017  0.008

# Montevideobus (lags=4)

In [298]:
data_monte = pd.read_csv('./simulation_results/Real_simulation/monte.csv')

In [301]:
data_monte_block = pd.read_csv('./simulation_results/Real_simulation/monte_block.csv')

## Baseline

In [299]:
round(data_monte.query("mrate==0")['mse'].mean(),3),round(data_monte.query("mrate==0")['mse'].std(),3)

(0.97, 0.024)

## Random

In [300]:
pd.merge(data_monte.query("mtype=='rand'").groupby(['mrate','lags','method'])['mse'].mean().reset_index(),
         data_monte.query("mtype=='rand'").groupby(['mrate','lags','method'])['mse'].std().reset_index(),
         on=['method','mrate','lags']).rename(columns={'mse_x':'mean','mse_y':'std'})

    mrate  lags    method      mean       std
0     0.3     4      GNAR  1.061937  0.000000
1     0.3     4  IT-STGCN  0.971925  0.001871
2     0.3     4     STGCN  0.965885  0.002552
3     0.3     8      GNAR  1.068464  0.000000
4     0.3     8  IT-STGCN  0.974867  0.003233
5     0.3     8     STGCN  0.972051  0.002383
6     0.4     4      GNAR  1.061937  0.000000
7     0.4     4  IT-STGCN  0.976348  0.001374
8     0.4     4     STGCN  0.967480  0.002974
9     0.4     8      GNAR  1.068464  0.000000
10    0.4     8  IT-STGCN  0.978809  0.002110
11    0.4     8     STGCN  0.973098  0.002613
12    0.8     4      GNAR  1.061937  0.000000
13    0.8     4  IT-STGCN  1.006583  0.003297
14    0.8     4     STGCN  0.999715  0.006909
15    0.8     8      GNAR  1.068464  0.000000
16    0.8     8  IT-STGCN  1.004450  0.002953
17    0.8     8     STGCN  1.005238  0.005777
18    0.9     4      GNAR  1.061937  0.000000
19    0.9     4  IT-STGCN  1.034162  0.005611
20    0.9     4     STGCN  1.034995  0.006551
21    0.9     8      GNAR  1.068464  0.000000
22    0.9     8  IT-STGCN  1.030283  0.007979
23    0.9     8     STGCN  1.031538  0.009285

## Block

In [303]:
pd.merge(data_monte_block.query("mtype=='block'").groupby(['mrate','lags','method'])['mse'].mean().reset_index(),
         data_monte_block.query("mtype=='block'").groupby(['mrate','lags','method'])['mse'].std().reset_index(),
         on=['method','mrate','lags']).rename(columns={'mse_x':'mean','mse_y':'std'})

      mrate  lags    method      mean       std
0  0.149142     4  IT-STGCN  0.964119  0.002208
1  0.149142     4     STGCN  0.965172  0.001673
2  0.149142     8  IT-STGCN  0.972110  0.002271
3  0.149142     8     STGCN  0.972060  0.001325